import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Navbar from "./components/Navbar";
import Navfoot from "./components/Navfoot";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark h-full">
      <body className={`${inter.className} dark h-full`}>
        <Navbar></Navbar>
        <NextUIProvider>
          {children}
        </NextUIProvider>
        <Navfoot></Navfoot>
      </body>
    </html>
  );
}
